### ISSUE TITLE
Compile warning

### ISSUE THREAD

**Issue by OvermindDL1** [BjRo/apex#19]
This seems like an important compile warning for apex:
```elixir
warning: function List.unzip/1 is undefined or private
  lib/apex/awesome_def.ex:52
```
And indeed, there is no List.unzip function in the Elixir module list.

**Comment by BjRo** [comment]
Thank you for noticing this. Actually, this seems to be broken since quite a while. A little digging revealed `List.unzip` was removed in the 1.0 release.

I just fixed this via https://github.com/BjRo/apex/commit/86df959a498cfcdb4c65dbb4c24ef59f29c7d6da

The fix is available on hex in the 1.5.1 version of the package.
